create table public.data_item (
                                  id bigint generated by default as identity,
                                  stash_key varchar(255) not null,
                                  stash_value varchar(255) not null,
                                  primary key (id)
);
